services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: wireless-heatmapper-web
    environment:
      HOSTNAME: 0.0.0.0
      NODE_ENV: development
      PORT: 3333
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    command: npm run dev
