BEGIN;

CREATE TYPE estado_proyecto AS ENUM (
    'nuevo',
    'en_progreso',
    'completado',
    'archivado'
);

CREATE TABLE usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(30) NOT NULL DEFAULT 'tecnico',
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    ultimo_acceso TIMESTAMPTZ
);

CREATE UNIQUE INDEX ix_usuario_email ON usuario (email);
CREATE INDEX ix_usuario_id ON usuario (id);

CREATE TABLE cliente (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uq_cliente_nombre UNIQUE (nombre)
);

CREATE INDEX ix_cliente_id ON cliente (id);

CREATE TABLE proyecto (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    descripcion VARCHAR(500),
    cliente_id INTEGER,
    estado estado_proyecto NOT NULL DEFAULT 'nuevo',
    tecnico_id INTEGER NOT NULL,
    ultima_actividad TIMESTAMPTZ DEFAULT NOW(),
    cantidad_puntos INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_proyecto_cliente_id
        FOREIGN KEY (cliente_id) REFERENCES cliente (id),
    CONSTRAINT fk_proyecto_tecnico_id
        FOREIGN KEY (tecnico_id) REFERENCES usuario (id)
);

CREATE INDEX ix_proyecto_id ON proyecto (id);
CREATE INDEX ix_proyecto_tecnico_id ON proyecto (tecnico_id);
CREATE INDEX ix_proyecto_cliente_id ON proyecto (cliente_id);

CREATE TABLE refresh_token (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(64) NOT NULL,
    usuario_id INTEGER NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_refresh_token_usuario_id
        FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix_refresh_token_token ON refresh_token (token);
CREATE INDEX ix_refresh_token_id ON refresh_token (id);
CREATE INDEX ix_refresh_token_usuario_id ON refresh_token (usuario_id);

COMMIT;
