"""init_vacia

Revision ID: 073ed4d23a33
Revises:
Create Date: 2026-04-24 12:23:03.961245
"""

from collections.abc import Sequence

revision: str = "073ed4d23a33"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
