"""sp1_agregar_descripcion_proyecto

Revision ID: 83b6c2b1a08c
Revises: f6a7b8c9d0e1
Create Date: 2026-04-25 05:11:46.069865
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "83b6c2b1a08c"
down_revision: str | None = "f6a7b8c9d0e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "proyecto", sa.Column("descripcion", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("proyecto", "descripcion")
    # ### end Alembic commands ###
